// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing_cycles.sql

package dbmodels

import (
	"context"
	"time"

	"eats/backend/common/shared"
	"eats/backend/settlements/app/models"
	"eats/backend/settlements/domain"
	"github.com/shopspring/decimal"
)

const billingCyclesByPartnerUUID = `-- name: BillingCyclesByPartnerUUID :many
SELECT billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date
FROM settlements.billing_cycles
WHERE partner_uuid = $1
ORDER BY billing_cycle_number DESC
`

func (q *Queries) BillingCyclesByPartnerUUID(ctx context.Context, partnerUuid domain.LegalEntityUUID) ([]SettlementsBillingCycle, error) {
	rows, err := q.db.Query(ctx, billingCyclesByPartnerUUID, partnerUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsBillingCycle{}
	for rows.Next() {
		var i SettlementsBillingCycle
		if err := rows.Scan(
			&i.BillingCycleUuid,
			&i.PartnerUuid,
			&i.PartnerType,
			&i.BillingCycleNumber,
			&i.Closed,
			&i.Settled,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderBreakdownsByBillingCycleUUID = `-- name: OrderBreakdownsByBillingCycleUUID :many
SELECT ob.order_uuid, ob.breakdown_type, ob.net_amount, ob.tax_amount, ob.gross_amount
FROM settlements.order_breakdowns ob
INNER JOIN settlements.billing_cycle_orders bco USING (order_uuid)
WHERE bco.billing_cycle_uuid = $1
`

func (q *Queries) OrderBreakdownsByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) ([]SettlementsOrderBreakdown, error) {
	rows, err := q.db.Query(ctx, orderBreakdownsByBillingCycleUUID, billingCycleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettlementsOrderBreakdown{}
	for rows.Next() {
		var i SettlementsOrderBreakdown
		if err := rows.Scan(
			&i.OrderUuid,
			&i.BreakdownType,
			&i.NetAmount,
			&i.TaxAmount,
			&i.GrossAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordersByBillingCycleUUID = `-- name: OrdersByBillingCycleUUID :many
SELECT orders.order_uuid, restaurant_uuid, courier_uuid, currency, commission_net_amount, ordered_at, billing_cycle_uuid, billing_cycle_orders.order_uuid FROM settlements.orders
INNER JOIN settlements.billing_cycle_orders USING (order_uuid)
WHERE billing_cycle_uuid = $1
`

type OrdersByBillingCycleUUIDRow struct {
	OrderUuid           models.OrderUUID
	RestaurantUuid      domain.LegalEntityUUID
	CourierUuid         domain.LegalEntityUUID
	Currency            shared.Currency
	CommissionNetAmount decimal.Decimal
	OrderedAt           time.Time
	BillingCycleUuid    domain.BillingCycleUUID
	OrderUuid_2         models.OrderUUID
}

func (q *Queries) OrdersByBillingCycleUUID(ctx context.Context, billingCycleUuid domain.BillingCycleUUID) ([]OrdersByBillingCycleUUIDRow, error) {
	rows, err := q.db.Query(ctx, ordersByBillingCycleUUID, billingCycleUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrdersByBillingCycleUUIDRow{}
	for rows.Next() {
		var i OrdersByBillingCycleUUIDRow
		if err := rows.Scan(
			&i.OrderUuid,
			&i.RestaurantUuid,
			&i.CourierUuid,
			&i.Currency,
			&i.CommissionNetAmount,
			&i.OrderedAt,
			&i.BillingCycleUuid,
			&i.OrderUuid_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBillingCycle = `-- name: SaveBillingCycle :exec
INSERT INTO settlements.billing_cycles (billing_cycle_uuid, partner_uuid, partner_type, billing_cycle_number, closed, settled, start_date, end_date)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
       )
ON CONFLICT (billing_cycle_uuid) DO UPDATE SET
   -- Other fields are immutable
    closed = EXCLUDED.closed,
    settled = EXCLUDED.settled,
    end_date = EXCLUDED.end_date
`

type SaveBillingCycleParams struct {
	BillingCycleUuid   domain.BillingCycleUUID
	PartnerUuid        domain.LegalEntityUUID
	PartnerType        domain.PartnerType
	BillingCycleNumber int32
	Closed             bool
	Settled            bool
	StartDate          time.Time
	EndDate            *time.Time
}

func (q *Queries) SaveBillingCycle(ctx context.Context, arg SaveBillingCycleParams) error {
	_, err := q.db.Exec(ctx, saveBillingCycle,
		arg.BillingCycleUuid,
		arg.PartnerUuid,
		arg.PartnerType,
		arg.BillingCycleNumber,
		arg.Closed,
		arg.Settled,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
